larg = float(input('Qual a largura da parede? '))
alt = float(input('Qual a altura da parede? '))
área = float(alt * larg)
tinta = (área / 2)
print('Sua parede tem a dimensão de {:.2f}x{:.2f} e sua área é de {:.2f}m².'.format(larg,alt,área))
print('Para pintar sera necessário {:.2f} Litros de tinta'.format(tinta))